apiVersion: apps/v1
kind: Deployment
metadata:
  name: abap-mock-in-go
  labels:
    app: abap-mock-in-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abap-mock-in-go
  template:
    metadata:
      labels:
        app: abap-mock-in-go
    spec:
      containers:
        - image: lechnerc77/abap-mock-in-go:0.0.2
          imagePullPolicy: Always
          name: abap-mock-in-go
          ports:
            - name: http
              containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: abap-mock-in-go
  labels:
    app: abap-mock-in-go
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: abap-mock-in-go
